name: chromo_digital
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # localization
  easy_localization: ^3.0.7
  # state management
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  bloc_state_gen: 1.0.0
  bloc_concurrency: ^0.2.5

  #pdf management
  syncfusion_flutter_pdf: ^28.1.37
  pdf:
  syncfusion_flutter_pdfviewer: ^28.1.37
  open_file: ^3.2.1
  path_provider: ^2.1.5
  # dependency injection
  get_it: ^8.0.2
  injectable: ^2.5.0
  # assets management
  flutter_gen: ^5.8.0
  # svg and image
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  ionicons: ^0.2.2
  # navigation
  auto_route: ^9.2.2
  # logger
  logger: ^2.5.0

  # storage
  sqflite: ^2.4.1
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2

  # helping hand
  json_annotation: ^4.9.0
  collection: 1.19.0
  equatable: ^2.0.7
  package_info_plus: ^8.1.2
  path: 1.9.0
  dropdown_button2: ^2.3.9
  country_code_picker: ^3.1.0

  fluttertoast: ^8.2.8
  permission_handler: ^11.3.1
  skeletonizer: ^1.4.2

  lucide_icons_flutter: ^1.2.5

  # api client
  dio: ^5.7.0
  flutter_dotenv: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0

  photo_manager: ^3.6.3
  image_picker: ^1.1.2
  syncfusion_flutter_signaturepad: ^28.1.37
  signature: ^4.0.0
  intl: any
  flutter_email_sender: ^6.0.3
  file_picker: ^8.1.7

  extensions_plus: ^1.3.0

# overide dependency_overrides:
dependency_overrides:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  injectable_generator: ^2.6.2
  auto_route_generator: ^9.0.0
  json_serializable: ^6.8.0

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    #    - assets/svgs/
    # localization
    - assets/translations/
  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
